name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'


categories:
  - title: '💥 Breaking changes'
    labels:
      - 'breaking'
  - title: '✨ New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '⚠️ Deprecations'
    labels:
      - 'deprecation'
  - title: '📃 Documentation'
    labels:
      - 'documentation'
  - title: '🧩 Dependency Updates'
    labels:
      - 'dependencies'
      - 'github_actions'
    collapse-after: 5
  - title: '🧰 Maintenance'
    labels:
      - 'ci'
      - 'build'
  - title: '🔬 Other updates'
    labels:
      - 'style'
      - 'testing'
      - 'perfomance'
      - 'refactor'

autolabeler:
  - label: ':sparkles: feature'
    title:
      - '/adds/i'
      - '/add method/i'
  - label: ':ghost: bug'
    title:
      - '/fix/i'
  - label: ':rocket: code quality'
    title:
      - '/Refactor/i'
  - label: ':test_tube: testing'
    files:
      - 'test_*'
      - 'conftest.py'
  - label: ':book: documentation'
    title:
      - '/docs:/i'
    files:
      - '*.md'
      - 'mkdocs.yml'
  - label: ':construction_worker_woman: ci'
    title:
      - '/ci:/i'
    files:
      - '.github/*'
  - label: ':recycle: dependencies'
    title:
      - '/bump/i'
  - label: ':file_cabinet: deprecation'
    title:
      - '/Deprecate/i'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-contributors:
  - 'tr4nt0r'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  Contributors: $CONTRIBUTORS

  **Full Changelog**: $REPOSITORY/compare/$PREVIOUS_TAG...$NEXT_COMPLETE_VERSION
